--Old Paths from before self contained model
resource.AddFile("materials/navalwarfare/capture_ring2.vmt")
resource.AddFile("materials/navalwarfare/capture_ring2.vtf")
resource.AddFile("materials/navalwarfare/compass.vtf")
resource.AddFile("materials/navalwarfare/compass.vmt")


-- resource.AddFile("materials/navalwarfare/navalwarfare/vgui/entities/npc_ww2_ame_rifleman.vmt")
-- resource.AddFile("materials/navalwarfare/navalwarfare/vgui/entities/npc_ww2_ame_rifleman.vtf")
-- resource.AddFile("materials/navalwarfare/navalwarfare/vgui/entities/npc_ww2_ame_riflemanf.vmt")
-- resource.AddFile("materials/navalwarfare/navalwarfare/models/american/rifleman/american_body.vmt")
-- resource.AddFile("materials/navalwarfare/navalwarfare/models/american/rifleman/american_body.vtf")
-- resource.AddFile("materials/navalwarfare/models/american/rifleman/american_body_exp.vtf")
-- resource.AddFile("materials/navalwarfare/models/american/rifleman/american_body_normal.vtf")
-- resource.AddFile("materials/navalwarfare/models/american/rifleman/american_gear.vmt")
-- resource.AddFile("materials/navalwarfare/models/american/rifleman/american_gear.vtf")
-- resource.AddFile("materials/navalwarfare/models/american/rifleman/american_gear_exp.vtf")
-- resource.AddFile("materials/navalwarfare/models/american/rifleman/american_gear_normal.vtf")

-- resource.AddFile("materials/navalwarfare/vgui/entities/npc_ww2_ger_grenadier.vmt")
-- resource.AddFile("materials/navalwarfare/vgui/entities/npc_ww2_ger_grenadier.vtf")
-- resource.AddFile("materials/navalwarfare/vgui/entities/npc_ww2_ger_grenadierf.vmt")
-- resource.AddFile("materials/navalwarfare/models/german/grenadier/german_body.vmt")
-- resource.AddFile("materials/navalwarfare/models/german/grenadier/german_body.vtf")
-- resource.AddFile("materials/navalwarfare/models/german/grenadier/german_body_exp.vtf")
-- resource.AddFile("materials/navalwarfare/models/german/grenadier/german_body_normal.vtf")
-- resource.AddFile("materials/navalwarfare/models/german/grenadier/german_gear.vmt")
-- resource.AddFile("materials/navalwarfare/models/german/grenadier/german_gear.vtf")
-- resource.AddFile("materials/navalwarfare/models/german/grenadier/german_gear_exp.vtf")
-- resource.AddFile("materials/navalwarfare/models/german/grenadier/german_gear_normal.vtf")

-- resource.AddFile("gamemodes/navalwarfarebeta/content/models/american/Rifleman.mdl")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/vgui/entities/npc_ww2_ame_rifleman.vmt")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/vgui/entities/npc_ww2_ame_rifleman.vtf")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/vgui/entities/npc_ww2_ame_riflemanf.vmt")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/american/rifleman/american_body.vmt")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/american/rifleman/american_body.vtf")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/american/rifleman/american_body_exp.vtf")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/american/rifleman/american_body_normal.vtf")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/american/rifleman/american_gear.vmt")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/american/rifleman/american_gear.vtf")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/american/rifleman/american_gear_exp.vtf")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/american/rifleman/american_gear_normal.vtf")

-- resource.AddFile("gamemodes/navalwarfarebeta/content/models/german/Grenadier_playermodel.mdl")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/vgui/entities/npc_ww2_ger_grenadier.vmt")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/vgui/entities/npc_ww2_ger_grenadier.vtf")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/vgui/entities/npc_ww2_ger_grenadierf.vmt")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/german/grenadier/german_body.vmt")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/german/grenadier/german_body.vtf")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/german/grenadier/german_body_exp.vtf")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/german/grenadier/german_body_normal.vtf")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/german/grenadier/german_gear.vmt")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/german/grenadier/german_gear.vtf")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/german/grenadier/german_gear_exp.vtf")
-- resource.AddFile("gamemodes/navalwarfarebeta/content/materials/models/german/grenadier/german_gear_normal.vtf")